service: serverlessViaCep

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  profile: default

custom:
  serverless-offline:
    httpPort: 3031
    lambdaPort: 5001

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: cep/{cep}
          method: get

plugins:
  - serverless-offline
