org: reidn3r
app: serverless-learning
service: serverlessIbge

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
package:
  individually: true  
  excludeDevDependencies: true

plugins:
  - serverless-offline
  