org: reidn3r
app: serverless-learning
service: serverlessIbge

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

custom:
  serverless-offline:
    httpPort: 3032
    lambdaPort: 5000

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: ibge/{cidade}/{uf}
          method: get

package:
  individually: true  
  excludeDevDependencies: true

plugins:
  - serverless-offline
